### ISSUE TITLE
Curation: document user agent string for linkchecker

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/cereal#3]
[Item 18](https://github.com/clarin-eric/cereal/blob/2df9a2c05450d1b34479fd99ff6d1f071d801a15/curation-dashboard/markdown/faq.md?plain=1#L159) explains that "[the] Link Checker respects robots.txt", but it would be good to also give some concrete information on how to adapt one's robots.txt file to allow/disallow link checking.

**Comment by wowasa** [comment]
done - it's in the faq
