### ISSUE TITLE
Broken internal links on help page

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/cereal#7]
Three of the links in the [curation-web section of the help page](https://github.com/clarin-eric/cereal/blob/e5327c0a379e296f383961ce1a4336e09539f64a/curation-dashboard/markdown/help.md#curation-web) are broken. Specifically:

> presenting pre-computed statistics for [CMD profiles](https://curation.clarin.eu/profile/table)
> presenting pre-computed statistics for [collections](https://curation.clarin.eu/collection/table)
> presenting pre-computed statistics for [link checking](https://curation.clarin.eu/statistics) and a continuously generated statistics in detail view (hence values might differ if links of the provider have been checked in the meantime)

**Comment by wowasa** [comment]
fixed
